/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Branch = IDL.Variant({
  'wadgaonSheri' : IDL.Null,
  'lohegaon' : IDL.Null,
});
export const Program = IDL.Variant({
  'playgroup' : IDL.Null,
  'juniorKg' : IDL.Null,
  'nursery' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'preferredBranch' : Branch,
  'preferredProgram' : Program,
  'email' : IDL.Text,
  'childAge' : IDL.Nat,
  'message' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Program,
        Branch,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Branch = IDL.Variant({
    'wadgaonSheri' : IDL.Null,
    'lohegaon' : IDL.Null,
  });
  const Program = IDL.Variant({
    'playgroup' : IDL.Null,
    'juniorKg' : IDL.Null,
    'nursery' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'preferredBranch' : Branch,
    'preferredProgram' : Program,
    'email' : IDL.Text,
    'childAge' : IDL.Nat,
    'message' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Program,
          Branch,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };